// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6vCkSvwPZLFf0RL42tHMFRT3fJ5FyloU',
    appId: '1:474569900608:web:973374ca79f50eca0155a5',
    messagingSenderId: '474569900608',
    projectId: 'barber-app-9d387',
    authDomain: 'barber-app-9d387.firebaseapp.com',
    storageBucket: 'barber-app-9d387.appspot.com',
    measurementId: 'G-GY69S448SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqgLivcbDNhnSb4b1O4dCqLtn464vINU',
    appId: '1:474569900608:android:3680b4fe5690dacf0155a5',
    messagingSenderId: '474569900608',
    projectId: 'barber-app-9d387',
    storageBucket: 'barber-app-9d387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEF1m8osgSpSEocsiT3NzEUqbXRcbWadA',
    appId: '1:474569900608:ios:20b37cc118c63f5a0155a5',
    messagingSenderId: '474569900608',
    projectId: 'barber-app-9d387',
    storageBucket: 'barber-app-9d387.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEF1m8osgSpSEocsiT3NzEUqbXRcbWadA',
    appId: '1:474569900608:ios:20b37cc118c63f5a0155a5',
    messagingSenderId: '474569900608',
    projectId: 'barber-app-9d387',
    storageBucket: 'barber-app-9d387.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6vCkSvwPZLFf0RL42tHMFRT3fJ5FyloU',
    appId: '1:474569900608:web:24b5db60b8049bd70155a5',
    messagingSenderId: '474569900608',
    projectId: 'barber-app-9d387',
    authDomain: 'barber-app-9d387.firebaseapp.com',
    storageBucket: 'barber-app-9d387.appspot.com',
    measurementId: 'G-DHLTQFZ6K4',
  );
}
